spring.application.name=Course API
#spring.security.user.name=sahus
#spring.security.user.password=saurabhsahu
management.endpoints.web.exposure.include=*
# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
# LDAP configuration
spring.ldap.embedded.ldif=classpath:ldap-data.ldif
spring.ldap.embedded.base-dn=dc=springframework,dc=org
spring.ldap.embedded.port=8389